### ISSUE TITLE
code

### ISSUE THREAD

**Issue by ximi2018** [IIE-MR/DIHN#1]
When will open source be available?

**Comment by yyc8763823DLU** [comment]
Same


------------------ 原始邮件 ------------------
发件人: "ximi2018"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 上午9:27
收件人: "IIE-MR/DIHN"<DIHN@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [IIE-MR/DIHN] code (#1)




When will open source be available?

**Comment by TreezzZ** [comment]
> When will open source be available?

CIFAR-10 version now is available, but due to lack of gpu, NUS-WIDE version code will be pushed later :(.

**Comment by TreezzZ** [comment]
NUS-WIDE version code is available now.
