### ISSUE TITLE
关于NUS-WIDE数据集训练

### ISSUE THREAD

**Issue by world2025** [IIE-MR/DIHN#2]
您好！非常感谢您的代码，我在训练NUS-WIDE数据集时出现一个错误，找不到database_img.txt，我查看了代码：
  retrieval_img_txt_path = os.path.join(root, 'database_img.txt')
  retrieval_label_txt_path = os.path.join(root, 'database_label_onehot.txt')
   query_img_txt_path = os.path.join(root, 'test_img.txt')
   query_label_txt_path = os.path.join(root, 'test_label_onehot.txt')
这几个文件都么有，请问在运行run.py文件时有做其他数据预处理吗？谢谢！

**Comment by TreezzZ** [comment]
> 您好！非常感谢您的代码，我在训练NUS-WIDE数据集时出现一个错误，找不到database_img.txt，我查看了代码：
> retrieval_img_txt_path = os.path.join(root, 'database_img.txt')
> retrieval_label_txt_path = os.path.join(root, 'database_label_onehot.txt')
> query_img_txt_path = os.path.join(root, 'test_img.txt')
> query_label_txt_path = os.path.join(root, 'test_label_onehot.txt')
> 这几个文件都么有，请问在运行run.py文件时有做其他数据预处理吗？谢谢！

https://pan.baidu.com/s/1Hr-WM108WgmnhMAmDM0pfA 提取码: xrqd，解压后放到nus-wide数据集目录下，可能我压缩文件的时候没把这几个文件放进去，抱歉。如果还是不行的话我重新打包一份数据集上传。

**Comment by world2025** [comment]
@TreezzZ 好的，谢谢
